### ISSUE TITLE
The minisat solver used in NeuroSAT

### ISSUE THREAD

**Issue by lee-man** [ryanzhangfan/NeuroSAT#4]
Hi Fan,

Thanks for your excellent PyTorch implementation of NeuroSAT. I checked the original repo and yours, and it seems that both repos use a python lib "PyMiniSolvers" to generate the labels for SAT problems. I am wondering is this lib the same as the one on [PyMiniSolvers](https://github.com/liffiton/PyMiniSolvers) Thanks!

Min

**Comment by ryanzhangfan** [comment]
Yes. You can check **setup.sh** to get more details: both repos clone "PyMiniSolvers" from https://github.com/liffiton/PyMiniSolvers.

**Comment by lee-man** [comment]
Got it! Thanks for your prompt reply!
