### ISSUE TITLE
How to use the layernorm?

### ISSUE THREAD

**Issue by lee-man** [ryanzhangfan/NeuroSAT#6]
Hi,

Sorry to bother you again. Recently I started to refactor the related code using the PyTorch Geometric. And I try to add an option to support the layer-norm for the LSTM. I saw there was the definition of such layer in your code and was not used. Could you share the way to use the layer-norm in your code? Thanks a lot!

Min

**Comment by ryanzhangfan** [comment]
@lee-man [LayerNormLSTMCell](https://arxiv.org/pdf/1607.06450.pdf) is used in the official tensorflow version NeuroSAT and it's different from simply using a LSTM cell followed by a LayerNorm. LayerNormLSTMCell is not officially supported in [PyTorch](https://github.com/pytorch/pytorch/issues/6760). So if you want to use LayerNormLSTM as the tensorflow version NeuroSAT, you have to implement it by yourself, or using a third-party implemented version, e.g. [url1](https://github.com/lmnt-com/haste), [url2](https://github.com/seba-1511/lstms.pth).
p.s. The above two links are found randomly and this doesn't mean that they are recommended third-party implementations. Please check the correctness and validity before use.

**Comment by lee-man** [comment]
@ryanzhangfan Thanks for your reply! I will check them out.
