### ISSUE TITLE
How do I install the PyMiniSolvers library?

### ISSUE THREAD

**Issue by zwd2016** [ryanzhangfan/NeuroSAT#8]
Dear author,

I typed the pip install PyMiniSolvers command in my conda virtual environment indicating that there is no corresponding version of this third-party library. And I didn't find anything in the pypi website. I hope I can get your help. Have a nice day!

**Comment by ryanzhangfan** [comment]
Please follow the instruction of [setup.sh](https://github.com/ryanzhangfan/NeuroSAT/blob/master/setup.sh) to install the PyMiniSolvers.

**Comment by zwd2016** [comment]
> Please follow the instruction of [setup.sh](https://github.com/ryanzhangfan/NeuroSAT/blob/master/setup.sh) to install the PyMiniSolvers.

Thanks！Already solved my problem.
